name: Build and deploy site

on:
  push:
    branches: ["master"]
  # Allow running the workflow manually
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Prevent concurrent workflows but don't interrupt the one currently running
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install pandoc
        uses: pandoc/actions/setup@v1
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build site
        run: BUILD_ENV=prod make all
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/site # Default: `_site/`
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
